export const CHANGE_PLACE = "CHANGE_PLACE";
export const CHANGE_STARTDATE = "CHANGE_STARTDATE";
export const CHANGE_ENDDATE = "CHANGE_ENDDATE";
export const CHANGE_GUEST = "CHANGE_GUEST";

export const ADD_ROOM = 'ADD_ROOM'
export const DELETE_ROOM = 'DELETE_ROOM'
export const UPDATE_ROOM = 'UPDATE_ROOM'
export const GET_ROOM = 'GET_ROOM'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const LOG_OUT = 'LOG_OUT'
export const USER_UPDATE_INFO = 'USER_UPDATE_INFO'
export const GET_USER = 'GET_USER'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'




export const GET_RENTAL = 'GET_RENTAL';
export const POST_RENTAL = 'POST_RENTAL';

export const GET_ARRIVING_ROOMS = 'GET_ARRIVING_ROOMS';
export const GET_CHECKING_OUT_ROOMS = 'GET_CHECKING_OUT_ROOMS';
export const GET_CURRENTLY_HOSTING_ROOMS = 'GET_CURRENTLY_HOSTING_ROOMS';
export const GET_EMPTY_ROOMS = 'GET_EMPTY_ROOMS';

