export const CHANGE_PLACE = "CHANGE_PLACE";
export const CHANGE_STARTDATE = "CHANGE_STARTDATE";
export const CHANGE_ENDDATE = "CHANGE_ENDDATE";
export const CHANGE_ADULT_GUEST = "CHANGE_ADULT_GUEST";
export const CHANGE_CHILD_GUEST = "CHANGE_CHILD_GUEST";
export const CHANGE_BABY_GUEST = "CHANGE_BABY_GUEST";
